export const CONFIG = {
    variables: {
        reporters: ["Sergio Terrero", "Pedro Martinez", "Eugenia Derbez", "Jackie Perex", "Pamela Alvarez"],
        difficultyLevels: ["Low", "Medium", "High", "Critical"],
        workTypes: ["Story", "Bug", "Non-prod", "Tasks", "Tech Debt", "Spike", "Feature", "Epic"],
        developmentTypes: ["Frontend", "Backend", "Fullstack"],
        status: ["Backlog", "Blocked", "To Do", "In Progress", "Demo Ready", "Completed", "Released"],

        statusLevel: ["Pending", "In Progress", "Completed",],
        repoNames: ["example1", "example2", "example3", "example4", "example5"],
        sprints: ['PL-001', 'P:-002'],
        activityType: [
            "1x1",
            "Standup",
            "Retros",
            "Planning",
            "Sprint Review",
            "Bi-weekly Demos",
            "Training",
            "Collaboration",
            "Mentor Meetings",
            "Mentee Meetings",
            "Workshops",
            "Feedback Exchange",
            "Brainstorming",
            "Presentation",
            "Problem Solving",
            "Team Building",
            "Pair Programming",
            "Volunteering Meetings",
            "Personal Development",
            "Professional Development",
            "ERG Meetings",
            "Ad Hoc Meetings",
            "Coffee Chats",
            "Lunch and Learn",
            "Sprint Review",
            "Town Hall",
            "Social Hour",
            "Follow up",
            "Onboarding",
            "Offboarding",
            "Other"
        ],
        eventTypes:[
  "ERG Events",
  "Volunteering",
  "Workshops",
  "Company Events",
  "Networking",
  "Hackathons",
  "Team Events",
  "Other"
],
        points: ['1', '2', '3', '5', '8', '13'],
        timeoffTypes: ["Vacation", "Sick Leave", "Personal Leave", "Compensatory Time Off", "Unpaid Leave", "Maternity/Paternity Leave", "Bereavement Leave", "Jury Duty", "Military Leave", "Public Service Leave", "Other"],
        currentWork: ["Story","Spike", "Feature", "Bug Fix", "Technical Debt", "Research", "Documentation", "Testing", "Code Review", "Deployment", "Maintenance", "Other"],
    },

};